/**
 * --------------------------------------------------------
 * This demo was created using amCharts V4 preview release./**
 * --------------------------------------------------------
 * This demo was created using amCharts V4 preview release.
 * 
 * V4 is the latest installement in amCharts data viz
 * library family, to be released in the first half of
 * 2018.
 *
 * For more information and documentation visit:
 * https://www.amcharts.com/docs/v4/
 * --------------------------------------------------------
 */


am4core.useTheme(am4themes_animated);
var chart = am4core.create("chartdiv", am4charts.ChordDiagram);


// colors of main characters
chart.colors.saturation = 0.40;
chart.colors.step = 0;
var colors = {}



chart.data = [
// node property fields take data from data items where they are first mentioned, that's 
// why we add empty data items at the beginning and set colors here

// real data

{"from":" ","to":" ","value":50,"color":"#FFFFFF"},
{"from":"Upogebia casis","to":"Upogebia casis","value":0,"color":"#3F9EA5"},
{"from":"Upogebia annae","to":"Upogebia annae","value":0,"color":"#3F9EA5"},
{"from":"Typton distinctus","to":"Typton distinctus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus yano","to":"Synalpheus yano","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus tenuispina","to":"Synalpheus tenuispina","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus ruetzleri","to":"Synalpheus ruetzleri","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus plumosetosus","to":"Synalpheus plumosetosus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus pectiniger","to":"Synalpheus pectiniger","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus kuadramanus","to":"Synalpheus kuadramanus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus irie","to":"Synalpheus irie","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus elizabethae","to":"Synalpheus elizabethae","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus dardeaui","to":"Synalpheus dardeaui","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus corallinus","to":"Synalpheus corallinus","value":0,"color":"#3F9EA5"},
{"from":"Stenothoe georgiana","to":"Stenothoe georgiana","value":0,"color":"#3F9EA5"},
{"from":"Stenopus scutellatus","to":"Stenopus scutellatus","value":0,"color":"#3F9EA5"},
{"from":"Seba sp. B","to":"Seba sp. B","value":0,"color":"#3F9EA5"},
{"from":"Seba sp. A","to":"Seba sp. A","value":0,"color":"#3F9EA5"},
{"from":"Seba sp.","to":"Seba sp.","value":0,"color":"#3F9EA5"},
{"from":"Seba alvarezi","to":"Seba alvarezi","value":0,"color":"#3F9EA5"},
{"from":"Pycnogonida sp.","to":"Pycnogonida sp.","value":0,"color":"#3F9EA5"},
{"from":"Pseudamphithoides bacescui","to":"Pseudamphithoides bacescui","value":0,"color":"#3F9EA5"},
{"from":"Podocerus brasiliensis","to":"Podocerus brasiliensis","value":0,"color":"#3F9EA5"},
{"from":"Platypodiella spectabilis","to":"Platypodiella spectabilis","value":0,"color":"#3F9EA5"},
{"from":"Pinnotheres shoemakeri","to":"Pinnotheres shoemakeri","value":0,"color":"#3F9EA5"},
{"from":"Petrolisthes caribensis","to":"Petrolisthes caribensis","value":0,"color":"#3F9EA5"},
{"from":"Periclimenes sp.","to":"Periclimenes sp.","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus chacei","to":"Periclimenaeus chacei","value":0,"color":"#3F9EA5"},
{"from":"Paraliomera longimana","to":"Paraliomera longimana","value":0,"color":"#3F9EA5"},
{"from":"Pagurus provenzanoi","to":"Pagurus provenzanoi","value":0,"color":"#3F9EA5"},
{"from":"Paguristes tortugae","to":"Paguristes tortugae","value":0,"color":"#3F9EA5"},
{"from":"Pachycheles monilifer","to":"Pachycheles monilifer","value":0,"color":"#3F9EA5"},
{"from":"Nikoides schmitti","to":"Nikoides schmitti","value":0,"color":"#3F9EA5"},
{"from":"Neopontonides beaufortensis","to":"Neopontonides beaufortensis","value":0,"color":"#3F9EA5"},
{"from":"Neogonodactylus oerstedii","to":"Neogonodactylus oerstedii","value":0,"color":"#3F9EA5"},
{"from":"Neogonodactylus austrinus","to":"Neogonodactylus austrinus","value":0,"color":"#3F9EA5"},
{"from":"Nebalia villalobosi","to":"Nebalia villalobosi","value":0,"color":"#3F9EA5"},
{"from":"Munida irrasa","to":"Munida irrasa","value":0,"color":"#3F9EA5"},
{"from":"Melybia thalamita","to":"Melybia thalamita","value":0,"color":"#3F9EA5"},
{"from":"Megalobrachium soriatum","to":"Megalobrachium soriatum","value":0,"color":"#3F9EA5"},
{"from":"Lysmata pederseni","to":"Lysmata pederseni","value":0,"color":"#3F9EA5"},
{"from":"Libinia dubia","to":"Libinia dubia","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe wuriti","to":"Leucothoe wuriti","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe ubouhu","to":"Leucothoe ubouhu","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe saron","to":"Leucothoe saron","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe laurensi","to":"Leucothoe laurensi","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe flammosa","to":"Leucothoe flammosa","value":0,"color":"#3F9EA5"},
{"from":"Leptochela papulata","to":"Leptochela papulata","value":0,"color":"#3F9EA5"},
{"from":"Lepas (Anatifa) anatifera","to":"Lepas (Anatifa) anatifera","value":0,"color":"#3F9EA5"},
{"from":"Laticorophium baconi","to":"Laticorophium baconi","value":0,"color":"#3F9EA5"},
{"from":"Hourstonius tortugae","to":"Hourstonius tortugae","value":0,"color":"#3F9EA5"},
{"from":"Hoplopheonoides shoemakeri","to":"Hoplopheonoides shoemakeri","value":0,"color":"#3F9EA5"},
{"from":"Haustorius jayneae","to":"Haustorius jayneae","value":0,"color":"#3F9EA5"},
{"from":"Gonodactylus sp.","to":"Gonodactylus sp.","value":0,"color":"#3F9EA5"},
{"from":"Gnathophyllum americanum","to":"Gnathophyllum americanum","value":0,"color":"#3F9EA5"},
{"from":"Excorallana tricornis","to":"Excorallana tricornis","value":0,"color":"#3F9EA5"},
{"from":"Erichthonius sp. A","to":"Erichthonius sp. A","value":0,"color":"#3F9EA5"},
{"from":"Emerita benedicti","to":"Emerita benedicti","value":0,"color":"#3F9EA5"},
{"from":"Elasmopus thomasi","to":"Elasmopus thomasi","value":0,"color":"#3F9EA5"},
{"from":"Elasmopus rapax","to":"Elasmopus rapax","value":0,"color":"#3F9EA5"},
{"from":"Elasmopus mayo","to":"Elasmopus mayo","value":0,"color":"#3F9EA5"},
{"from":"Elasmopus levis","to":"Elasmopus levis","value":0,"color":"#3F9EA5"},
{"from":"Elasmopus balkomanus","to":"Elasmopus balkomanus","value":0,"color":"#3F9EA5"},
{"from":"Dromia erythropus","to":"Dromia erythropus","value":0,"color":"#3F9EA5"},
{"from":"Deutella incerta","to":"Deutella incerta","value":0,"color":"#3F9EA5"},
{"from":"Curidia debrogania","to":"Curidia debrogania","value":0,"color":"#3F9EA5"},
{"from":"Colomastix sarae","to":"Colomastix sarae","value":0,"color":"#3F9EA5"},
{"from":"Colomastix janiceae","to":"Colomastix janiceae","value":0,"color":"#3F9EA5"},
{"from":"Colomastix gibbosa","to":"Colomastix gibbosa","value":0,"color":"#3F9EA5"},
{"from":"Colomastix escobarae","to":"Colomastix escobarae","value":0,"color":"#3F9EA5"},
{"from":"Cirolana parva","to":"Cirolana parva","value":0,"color":"#3F9EA5"},
{"from":"Chondrochelia savignyi","to":"Chondrochelia savignyi","value":0,"color":"#3F9EA5"},
{"from":"Calcinus tibicen","to":"Calcinus tibicen","value":0,"color":"#3F9EA5"},
{"from":"Calaxius inaequalis","to":"Calaxius inaequalis","value":0,"color":"#3F9EA5"},
{"from":"Brachycarpus biunguiculatus","to":"Brachycarpus biunguiculatus","value":0,"color":"#3F9EA5"},
{"from":"Bemlos setosus","to":"Bemlos setosus","value":0,"color":"#3F9EA5"},
{"from":"Batea cuspidata","to":"Batea cuspidata","value":0,"color":"#3F9EA5"},
{"from":"Apolochus delacaya","to":"Apolochus delacaya","value":0,"color":"#3F9EA5"},
{"from":"Ampithoe sp. A","to":"Ampithoe sp. A","value":0,"color":"#3F9EA5"},
{"from":"Ampithoe ramondi","to":"Ampithoe ramondi","value":0,"color":"#3F9EA5"},
{"from":"Ampelisca verrilli","to":"Ampelisca verrilli","value":0,"color":"#3F9EA5"},
{"from":"Alpheus normanni","to":"Alpheus normanni","value":0,"color":"#3F9EA5"},
{"from":"Alpheus formosus","to":"Alpheus formosus","value":0,"color":"#3F9EA5"},
{"from":"Alpheus floridanus","to":"Alpheus floridanus","value":0,"color":"#3F9EA5"},
{"from":"Alpheus cylindricus","to":"Alpheus cylindricus","value":0,"color":"#3F9EA5"},
{"from":"Alpheus angulosus","to":"Alpheus angulosus","value":0,"color":"#3F9EA5"},
{"from":"Upogebia acanthura","to":"Upogebia acanthura","value":0,"color":"#3F9EA5"},
{"from":"Typton tortugae","to":"Typton tortugae","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus williamsi","to":"Synalpheus williamsi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus microneptunus","to":"Synalpheus microneptunus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus idios","to":"Synalpheus idios","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus hoetjesi","to":"Synalpheus hoetjesi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus duffyi","to":"Synalpheus duffyi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus carpenteri","to":"Synalpheus carpenteri","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus brevifrons","to":"Synalpheus brevifrons","value":0,"color":"#3F9EA5"},
{"from":"Pilumnus sp.","to":"Pilumnus sp.","value":0,"color":"#3F9EA5"},
{"from":"Pilumnus dasypodus","to":"Pilumnus dasypodus","value":0,"color":"#3F9EA5"},
{"from":"Petrolisthes politus","to":"Petrolisthes politus","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus wilsoni","to":"Periclimenaeus wilsoni","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus pearsei","to":"Periclimenaeus pearsei","value":0,"color":"#3F9EA5"},
{"from":"Pachycheles sp.","to":"Pachycheles sp.","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe garifunae","to":"Leucothoe garifunae","value":0,"color":"#3F9EA5"},
{"from":"Gammarus palustris","to":"Gammarus palustris","value":0,"color":"#3F9EA5"},
{"from":"Discias serratirostris","to":"Discias serratirostris","value":0,"color":"#3F9EA5"},
{"from":"Colomastix tridentata","to":"Colomastix tridentata","value":0,"color":"#3F9EA5"},
{"from":"Colomastix sp. B","to":"Colomastix sp. B","value":0,"color":"#3F9EA5"},
{"from":"Colomastix cornuticauda","to":"Colomastix cornuticauda","value":0,"color":"#3F9EA5"},
{"from":"Amphithoe sp.","to":"Amphithoe sp.","value":0,"color":"#3F9EA5"},
{"from":"Alpheus cristulifrons","to":"Alpheus cristulifrons","value":0,"color":"#3F9EA5"},
{"from":"Alpheopsis labis","to":"Alpheopsis labis","value":0,"color":"#3F9EA5"},
{"from":"Typton prionurus","to":"Typton prionurus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus scaphoceris","to":"Synalpheus scaphoceris","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus dominicensis","to":"Synalpheus dominicensis","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus bocas","to":"Synalpheus bocas","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus belizensis","to":"Synalpheus belizensis","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus apioceros","to":"Synalpheus apioceros","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus agelas","to":"Synalpheus agelas","value":0,"color":"#3F9EA5"},
{"from":"Stenetriidae incertae sedis occidentale","to":"Stenetriidae incertae sedis occidentale","value":0,"color":"#3F9EA5"},
{"from":"Processa fimbriata","to":"Processa fimbriata","value":0,"color":"#3F9EA5"},
{"from":"Paracerceis caudata","to":"Paracerceis caudata","value":0,"color":"#3F9EA5"},
{"from":"Pachycheles ackleianus","to":"Pachycheles ackleianus","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe barana","to":"Leucothoe barana","value":0,"color":"#3F9EA5"},
{"from":"Holthuisaeus bermudensis","to":"Holthuisaeus bermudensis","value":0,"color":"#3F9EA5"},
{"from":"Ericthonius brasiliensis","to":"Ericthonius brasiliensis","value":0,"color":"#3F9EA5"},
{"from":"Alcirona krebsii","to":"Alcirona krebsii","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus thele","to":"Synalpheus thele","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus herricki","to":"Synalpheus herricki","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus heardi","to":"Synalpheus heardi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus androsi","to":"Synalpheus androsi","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus schmitti","to":"Periclimenaeus schmitti","value":0,"color":"#3F9EA5"},
{"from":"Mithrax forceps","to":"Mithrax forceps","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe kensleyi","to":"Leucothoe kensleyi","value":0,"color":"#3F9EA5"},
{"from":"Leptochelia sp.","to":"Leptochelia sp.","value":0,"color":"#3F9EA5"},
{"from":"Excirolana mayana","to":"Excirolana mayana","value":0,"color":"#3F9EA5"},
{"from":"Colomastix irciniae","to":"Colomastix irciniae","value":0,"color":"#3F9EA5"},
{"from":"Colomastix halichondriae","to":"Colomastix halichondriae","value":0,"color":"#3F9EA5"},
{"from":"Colomastix falcirama","to":"Colomastix falcirama","value":0,"color":"#3F9EA5"},
{"from":"Apanthura sp.","to":"Apanthura sp.","value":0,"color":"#3F9EA5"},
{"from":"Ampithoe sp.","to":"Ampithoe sp.","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus rathbunae","to":"Synalpheus rathbunae","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus longicarpus","to":"Synalpheus longicarpus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus hemphilli","to":"Synalpheus hemphilli","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus goodei","to":"Synalpheus goodei","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus filidigitus","to":"Synalpheus filidigitus","value":0,"color":"#3F9EA5"},
{"from":"Parahaustorius attenuatus","to":"Parahaustorius attenuatus","value":0,"color":"#3F9EA5"},
{"from":"Carpias bermudensis","to":"Carpias bermudensis","value":0,"color":"#3F9EA5"},
{"from":"Balanus spongicola","to":"Balanus spongicola","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus regalis","to":"Synalpheus regalis","value":0,"color":"#3F9EA5"},
{"from":"Pagurus brevidactylus","to":"Pagurus brevidactylus","value":0,"color":"#3F9EA5"},
{"from":"Colomastix heardi","to":"Colomastix heardi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus mcclendoni","to":"Synalpheus mcclendoni","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe ashleyae","to":"Leucothoe ashleyae","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus ul","to":"Synalpheus ul","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus brooksi","to":"Synalpheus brooksi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus bousfieldi","to":"Synalpheus bousfieldi","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus perlatus","to":"Periclimenaeus perlatus","value":0,"color":"#3F9EA5"},
{"from":"Anchistioides antiguensis","to":"Anchistioides antiguensis","value":0,"color":"#3F9EA5"},
{"from":"Thor manningi","to":"Thor manningi","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus sanctithomae","to":"Synalpheus sanctithomae","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus paraneptunus","to":"Synalpheus paraneptunus","value":0,"color":"#3F9EA5"},
{"from":"Periclimenes sandyi","to":"Periclimenes sandyi","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus bredini","to":"Periclimenaeus bredini","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus chacei","to":"Synalpheus chacei","value":0,"color":"#3F9EA5"},
{"from":"Periclimenes iridescens","to":"Periclimenes iridescens","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus minus","to":"Synalpheus minus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus pandionis","to":"Synalpheus pandionis","value":0,"color":"#3F9EA5"},
{"from":"Periclimenaeus caraibicus","to":"Periclimenaeus caraibicus","value":0,"color":"#3F9EA5"},
{"from":"Leucothoe spinicarpa","to":"Leucothoe spinicarpa","value":0,"color":"#3F9EA5"},
{"from":"Cuapetes americanus","to":"Cuapetes americanus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus fritzmuelleri","to":"Synalpheus fritzmuelleri","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus brevicarpus","to":"Synalpheus brevicarpus","value":0,"color":"#3F9EA5"},
{"from":"Synalpheus townsendi","to":"Synalpheus townsendi","value":0,"color":"#3F9EA5"},
{"from":"Artrhopoda","to":"Artrhopoda","value":5,"color":"#FFFFFF"},
{"from":"  ","to":"  ","value":50,"color":"#FFFFFF"},
{"from":"Haplosclerida","to":"Haplosclerida","value":8.5,"color":"#FFFFFF"},
{"from":"Callyspongia (Cladochalina) aculeata","to":"Callyspongia (Cladochalina) aculeata","value":0,"color":"#FBAF4F"},
{"from":"Callyspongia (Callyspongia) fallax","to":"Callyspongia (Callyspongia) fallax","value":0,"color":"#FBAF4F"},
{"from":"Neopetrosia proxima","to":"Neopetrosia proxima","value":0,"color":"#FBAF4F"},
{"from":"Neopetrosia subtriangularis","to":"Neopetrosia subtriangularis","value":0,"color":"#FBAF4F"},
{"from":"Amphimedon compressa","to":"Amphimedon compressa","value":0,"color":"#FBAF4F"},
{"from":"Niphates erecta","to":"Niphates erecta","value":0,"color":"#FBAF4F"},
{"from":"Amphimedon viridis","to":"Amphimedon viridis","value":0,"color":"#FBAF4F"},
{"from":"Calyx podatypa","to":"Calyx podatypa","value":0,"color":"#FBAF4F"},
{"from":"Neopetrosia rosariensis","to":"Neopetrosia rosariensis","value":0,"color":"#FBAF4F"},
{"from":"Niphates digitalis","to":"Niphates digitalis","value":0,"color":"#FBAF4F"},
{"from":"Xestospongia sp.","to":"Xestospongia sp.","value":0,"color":"#FBAF4F"},
{"from":"Callyspongia (Cladochalina) plicifera","to":"Callyspongia (Cladochalina) plicifera","value":0,"color":"#FBAF4F"},
{"from":"Chalinula variabilis","to":"Chalinula variabilis","value":0,"color":"#FBAF4F"},
{"from":"Haliclona (Haliclona) oculata","to":"Haliclona (Haliclona) oculata","value":0,"color":"#FBAF4F"},
{"from":"Oceanapia sp.","to":"Oceanapia sp.","value":0,"color":"#FBAF4F"},
{"from":"Niphates amorpha","to":"Niphates amorpha","value":0,"color":"#FBAF4F"},
{"from":"Callyspongia (Cladochalina) armigera","to":"Callyspongia (Cladochalina) armigera","value":0,"color":"#FBAF4F"},
{"from":"Poecilosclerida","to":"Poecilosclerida","value":7,"color":"#FFFFFF"},
{"from":"Mycale (Arenochalina) laxissima","to":"Mycale (Arenochalina) laxissima","value":0,"color":"#B66353"},
{"from":"Monanchora arbuscula","to":"Monanchora arbuscula","value":0,"color":"#B66353"},
{"from":"Tedania (Tedania) ignis","to":"Tedania (Tedania) ignis","value":0,"color":"#B66353"},
{"from":"Lissodendoryx (Lissodendoryx) colombiensis","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":0,"color":"#B66353"},
{"from":"Lissodendoryx (Lissodendoryx) strongylata","to":"Lissodendoryx (Lissodendoryx) strongylata","value":0,"color":"#B66353"},
{"from":"Lissodendoryx sp.","to":"Lissodendoryx sp.","value":0,"color":"#B66353"},
{"from":"Clathria (Clathria) foliacea","to":"Clathria (Clathria) foliacea","value":0,"color":"#B66353"},
{"from":"Clathria (Thalysias) curacaoensis","to":"Clathria (Thalysias) curacaoensis","value":0,"color":"#B66353"},
{"from":"Batzella sp.","to":"Batzella sp.","value":0,"color":"#B66353"},
{"from":"Mycale (Zygomycale) parishii","to":"Mycale (Zygomycale) parishii","value":0,"color":"#B66353"},
{"from":"Iotrochota birotulata","to":"Iotrochota birotulata","value":0,"color":"#B66353"},
{"from":"Desmapsamma anchorata","to":"Desmapsamma anchorata","value":0,"color":"#B66353"},
{"from":"Pandaros acanthifolium","to":"Pandaros acanthifolium","value":0,"color":"#B66353"},
{"from":"Phorbas amaranthus","to":"Phorbas amaranthus","value":0,"color":"#B66353"},
{"from":"Dictyoceratida","to":"Dictyoceratida","value":7,"color":"#FFFFFF"},
{"from":"Ircinia strobilina","to":"Ircinia strobilina","value":0,"color":"#F37941"},
{"from":"Hyattella intestinalis","to":"Hyattella intestinalis","value":0,"color":"#F37941"},
{"from":"Ircinia felix","to":"Ircinia felix","value":0,"color":"#F37941"},
{"from":"Ircinia campana","to":"Ircinia campana","value":0,"color":"#F37941"},
{"from":"Sarcotragus fasciculatus","to":"Sarcotragus fasciculatus","value":0,"color":"#F37941"},
{"from":"Hyrtios proteus","to":"Hyrtios proteus","value":0,"color":"#F37941"},
{"from":"Spongia (Spongia) officinalis","to":"Spongia (Spongia) officinalis","value":0,"color":"#F37941"},
{"from":"Spongia sp.","to":"Spongia sp.","value":0,"color":"#F37941"},
{"from":"Dysidea sp.","to":"Dysidea sp.","value":0,"color":"#F37941"},
{"from":"Dysidea variabilis","to":"Dysidea variabilis","value":0,"color":"#F37941"},
{"from":"Hyattella sp.","to":"Hyattella sp.","value":0,"color":"#F37941"},
{"from":"Ircinia sp.","to":"Ircinia sp.","value":0,"color":"#F37941"},
{"from":"Spongia (Spongia) obliqua","to":"Spongia (Spongia) obliqua","value":0,"color":"#F37941"},
{"from":"Spongia (Spongia) tubulifera","to":"Spongia (Spongia) tubulifera","value":0,"color":"#F37941"},
{"from":"Verongiida","to":"Verongiida","value":3.5,"color":"#FFFFFF"},
{"from":"Aiolochroia crassa","to":"Aiolochroia crassa","value":0,"color":"#A570AF"},
{"from":"Aplysina fistularis","to":"Aplysina fistularis","value":0,"color":"#A570AF"},
{"from":"Aplysina insularis","to":"Aplysina insularis","value":0,"color":"#A570AF"},
{"from":"Aplysina lacunosa","to":"Aplysina lacunosa","value":0,"color":"#A570AF"},
{"from":"Aplysina archeri","to":"Aplysina archeri","value":0,"color":"#A570AF"},
{"from":"Verongula reiswigi","to":"Verongula reiswigi","value":0,"color":"#A570AF"},
{"from":"Aplysina fulva","to":"Aplysina fulva","value":0,"color":"#A570AF"},
{"from":"Agelasida","to":"Agelasida","value":1.5,"color":"#FFFFFF"},
{"from":"Agelas dispar","to":"Agelas dispar","value":0,"color":"#4F6980"},
{"from":"Agelas clathrodes","to":"Agelas clathrodes","value":0,"color":"#4F6980"},
{"from":"Agelas sceptrum","to":"Agelas sceptrum","value":0,"color":"#4F6980"},
{"from":"Axinellida","to":"Axinellida","value":1.5,"color":"#FFFFFF"},
{"from":"Dragmacidon lunaecharta","to":"Dragmacidon lunaecharta","value":0,"color":"#849DB0"},
{"from":"Auletta sycinularia","to":"Auletta sycinularia","value":0,"color":"#849DB0"},
{"from":"Ectyoplasia ferox","to":"Ectyoplasia ferox","value":0,"color":"#849DB0"},
{"from":"Clionaida","to":"Clionaida","value":1.5,"color":"#FFFFFF"},
{"from":"Spheciospongia vesparium","to":"Spheciospongia vesparium","value":0,"color":"#638B66"},
{"from":"Cliona celata","to":"Cliona celata","value":0,"color":"#638B66"},
{"from":"Spirastrella sp.","to":"Spirastrella sp.","value":0,"color":"#638B66"},
{"from":"Tetractinellida","to":"Tetractinellida","value":1,"color":"#FFFFFF"},
{"from":"Geodia gibberosa","to":"Geodia gibberosa","value":0,"color":"#7E756D"},
{"from":"Geodia neptuni","to":"Geodia neptuni","value":0,"color":"#7E756D"},
{"from":"Biemnida","to":"Biemnida","value":1.5,"color":"#FFFFFF"},
{"from":"Neofibularia nolitangere","to":"Neofibularia nolitangere","value":0,"color":"#A1CDA9"},
{"from":"Dendroceratida","to":"Dendroceratida","value":.5,"color":"#FFFFFF"},
{"from":"Igernella notabilis","to":"Igernella notabilis","value":0,"color":"#BFBB5F"},
{"from":"Suberitida","to":"Suberitida","value":.5,"color":"#FFFFFF"},
{"from":"Hymeniacidon caerulea","to":"Hymeniacidon caerulea","value":0,"color":"#D6CE9F"},
{"from":"Alcirona krebsii","to":"Agelas dispar","value":1},
{"from":"Alcirona krebsii","to":"Aplysina insularis","value":1},
{"from":"Alcirona krebsii","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Alpheopsis labis","to":"Agelas dispar","value":1},
{"from":"Alpheopsis labis","to":"Geodia gibberosa","value":1},
{"from":"Alpheus angulosus","to":"Niphates erecta","value":1},
{"from":"Alpheus cristulifrons","to":"Aplysina archeri","value":1},
{"from":"Alpheus cristulifrons","to":"Aplysina lacunosa","value":1},
{"from":"Alpheus cylindricus","to":"Spheciospongia vesparium","value":1},
{"from":"Alpheus floridanus","to":"Agelas dispar","value":1},
{"from":"Alpheus formosus","to":"Ircinia strobilina","value":1},
{"from":"Alpheus normanni","to":"Spheciospongia vesparium","value":1},
{"from":"Ampelisca verrilli","to":"Aiolochroia crassa","value":1},
{"from":"Amphithoe sp.","to":"Aiolochroia crassa","value":1},
{"from":"Amphithoe sp.","to":"Ircinia felix","value":1},
{"from":"Ampithoe ramondi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Ampithoe sp.","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Ampithoe sp.","to":"Cliona celata","value":1},
{"from":"Ampithoe sp.","to":"Dragmacidon lunaecharta","value":1},
{"from":"Ampithoe sp.","to":"Ircinia strobilina","value":1},
{"from":"Ampithoe sp. A","to":"Ircinia campana","value":1},
{"from":"Anchistioides antiguensis","to":"Aiolochroia crassa","value":1},
{"from":"Anchistioides antiguensis","to":"Aplysina fistularis","value":1},
{"from":"Anchistioides antiguensis","to":"Aplysina lacunosa","value":1},
{"from":"Anchistioides antiguensis","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Anchistioides antiguensis","to":"Callyspongia (Cladochalina) plicifera","value":1},
{"from":"Anchistioides antiguensis","to":"Clathria (Clathria) foliacea","value":1},
{"from":"Anchistioides antiguensis","to":"Ircinia strobilina","value":1},
{"from":"Anchistioides antiguensis","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Apanthura sp.","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Apanthura sp.","to":"Dragmacidon lunaecharta","value":1},
{"from":"Apanthura sp.","to":"Ircinia felix","value":1},
{"from":"Apanthura sp.","to":"Ircinia strobilina","value":1},
{"from":"Apolochus delacaya","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Balanus spongicola","to":"Amphimedon compressa","value":1},
{"from":"Balanus spongicola","to":"Aplysina fistularis","value":1},
{"from":"Balanus spongicola","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Balanus spongicola","to":"Dragmacidon lunaecharta","value":1},
{"from":"Balanus spongicola","to":"Ircinia strobilina","value":1},
{"from":"Batea cuspidata","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Bemlos setosus","to":"Amphimedon viridis","value":1},
{"from":"Brachycarpus biunguiculatus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Calaxius inaequalis","to":"Spheciospongia vesparium","value":1},
{"from":"Calcinus tibicen","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Carpias bermudensis","to":"Agelas dispar","value":1},
{"from":"Carpias bermudensis","to":"Aplysina insularis","value":1},
{"from":"Carpias bermudensis","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Carpias bermudensis","to":"Cliona celata","value":1},
{"from":"Carpias bermudensis","to":"Ircinia campana","value":1},
{"from":"Chondrochelia savignyi","to":"Dragmacidon lunaecharta","value":1},
{"from":"Cirolana parva","to":"Agelas dispar","value":1},
{"from":"Colomastix cornuticauda","to":"Agelas dispar","value":1},
{"from":"Colomastix cornuticauda","to":"Aplysina fistularis","value":1},
{"from":"Colomastix escobarae","to":"Desmapsamma anchorata","value":1},
{"from":"Colomastix falcirama","to":"Agelas dispar","value":1},
{"from":"Colomastix falcirama","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Colomastix falcirama","to":"Ircinia strobilina","value":1},
{"from":"Colomastix falcirama","to":"Niphates digitalis","value":1},
{"from":"Colomastix gibbosa","to":"Geodia gibberosa","value":1},
{"from":"Colomastix halichondriae","to":"Agelas dispar","value":1},
{"from":"Colomastix halichondriae","to":"Amphimedon compressa","value":1},
{"from":"Colomastix halichondriae","to":"Geodia gibberosa","value":1},
{"from":"Colomastix halichondriae","to":"Niphates erecta","value":1},
{"from":"Colomastix heardi","to":"Agelas dispar","value":1},
{"from":"Colomastix heardi","to":"Aplysina fistularis","value":1},
{"from":"Colomastix heardi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Colomastix heardi","to":"Geodia gibberosa","value":1},
{"from":"Colomastix heardi","to":"Ircinia felix","value":1},
{"from":"Colomastix heardi","to":"Spheciospongia vesparium","value":1},
{"from":"Colomastix irciniae","to":"Aplysina fistularis","value":1},
{"from":"Colomastix irciniae","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Colomastix irciniae","to":"Ircinia felix","value":1},
{"from":"Colomastix irciniae","to":"Ircinia strobilina","value":1},
{"from":"Colomastix janiceae","to":"Amphimedon compressa","value":1},
{"from":"Colomastix sarae","to":"Amphimedon compressa","value":1},
{"from":"Colomastix sp. B","to":"Cliona celata","value":1},
{"from":"Colomastix sp. B","to":"Haliclona (Haliclona) oculata","value":1},
{"from":"Colomastix tridentata","to":"Aplysina fistularis","value":1},
{"from":"Colomastix tridentata","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Cuapetes americanus","to":"Aiolochroia crassa","value":1},
{"from":"Cuapetes americanus","to":"Aplysina archeri","value":1},
{"from":"Cuapetes americanus","to":"Aplysina insularis","value":1},
{"from":"Cuapetes americanus","to":"Batzella sp.","value":1},
{"from":"Cuapetes americanus","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Cuapetes americanus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Cuapetes americanus","to":"Callyspongia (Cladochalina) plicifera","value":1},
{"from":"Cuapetes americanus","to":"Clathria (Clathria) foliacea","value":1},
{"from":"Cuapetes americanus","to":"Dysidea sp.","value":1},
{"from":"Cuapetes americanus","to":"Dysidea variabilis","value":1},
{"from":"Cuapetes americanus","to":"Ircinia strobilina","value":1},
{"from":"Cuapetes americanus","to":"Monanchora arbuscula","value":1},
{"from":"Cuapetes americanus","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Curidia debrogania","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Deutella incerta","to":"Cliona celata","value":1},
{"from":"Discias serratirostris","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Discias serratirostris","to":"Spheciospongia vesparium","value":1},
{"from":"Dromia erythropus","to":"Ircinia strobilina","value":1},
{"from":"Elasmopus balkomanus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Elasmopus levis","to":"Amphimedon viridis","value":1},
{"from":"Elasmopus mayo","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Elasmopus rapax","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Elasmopus thomasi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Emerita benedicti","to":"Ircinia strobilina","value":1},
{"from":"Erichthonius sp. A","to":"Ircinia campana","value":1},
{"from":"Ericthonius brasiliensis","to":"Amphimedon viridis","value":1},
{"from":"Ericthonius brasiliensis","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Ericthonius brasiliensis","to":"Cliona celata","value":1},
{"from":"Excirolana mayana","to":"Agelas dispar","value":1},
{"from":"Excirolana mayana","to":"Dragmacidon lunaecharta","value":1},
{"from":"Excirolana mayana","to":"Ircinia felix","value":1},
{"from":"Excirolana mayana","to":"Ircinia strobilina","value":1},
{"from":"Excorallana tricornis","to":"Agelas dispar","value":1},
{"from":"Gammarus palustris","to":"Dragmacidon lunaecharta","value":1},
{"from":"Gammarus palustris","to":"Ircinia strobilina","value":1},
{"from":"Gnathophyllum americanum","to":"Ircinia strobilina","value":1},
{"from":"Gonodactylus sp.","to":"Aplysina lacunosa","value":1},
{"from":"Haustorius jayneae","to":"Ircinia strobilina","value":1},
{"from":"Holthuisaeus bermudensis","to":"Aplysina archeri","value":1},
{"from":"Holthuisaeus bermudensis","to":"Aplysina fistularis","value":1},
{"from":"Holthuisaeus bermudensis","to":"Aplysina lacunosa","value":1},
{"from":"Hoplopheonoides shoemakeri","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Hourstonius tortugae","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Laticorophium baconi","to":"Amphimedon viridis","value":1},
{"from":"Lepas (Anatifa) anatifera","to":"Ircinia felix","value":1},
{"from":"Leptochela papulata","to":"Ircinia strobilina","value":1},
{"from":"Leptochelia sp.","to":"Aplysina archeri","value":1},
{"from":"Leptochelia sp.","to":"Aplysina lacunosa","value":1},
{"from":"Leptochelia sp.","to":"Cliona celata","value":1},
{"from":"Leptochelia sp.","to":"Ircinia campana","value":1},
{"from":"Leucothoe ashleyae","to":"Aiolochroia crassa","value":1},
{"from":"Leucothoe ashleyae","to":"Amphimedon compressa","value":1},
{"from":"Leucothoe ashleyae","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe ashleyae","to":"Iotrochota birotulata","value":1},
{"from":"Leucothoe ashleyae","to":"Niphates digitalis","value":1},
{"from":"Leucothoe ashleyae","to":"Niphates erecta","value":1},
{"from":"Leucothoe ashleyae","to":"Tedania (Tedania) ignis","value":1},
{"from":"Leucothoe barana","to":"Amphimedon compressa","value":1},
{"from":"Leucothoe barana","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe barana","to":"Spheciospongia vesparium","value":1},
{"from":"Leucothoe flammosa","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe garifunae","to":"Desmapsamma anchorata","value":1},
{"from":"Leucothoe garifunae","to":"Iotrochota birotulata","value":1},
{"from":"Leucothoe kensleyi","to":"Aiolochroia crassa","value":1},
{"from":"Leucothoe kensleyi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe kensleyi","to":"Iotrochota birotulata","value":1},
{"from":"Leucothoe kensleyi","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Leucothoe laurensi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe saron","to":"Aiolochroia crassa","value":1},
{"from":"Leucothoe spinicarpa","to":"Aiolochroia crassa","value":1},
{"from":"Leucothoe spinicarpa","to":"Amphimedon compressa","value":1},
{"from":"Leucothoe spinicarpa","to":"Amphimedon viridis","value":1},
{"from":"Leucothoe spinicarpa","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Leucothoe spinicarpa","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Leucothoe spinicarpa","to":"Dragmacidon lunaecharta","value":1},
{"from":"Leucothoe spinicarpa","to":"Haliclona (Haliclona) oculata","value":1},
{"from":"Leucothoe spinicarpa","to":"Ircinia campana","value":1},
{"from":"Leucothoe spinicarpa","to":"Ircinia felix","value":1},
{"from":"Leucothoe spinicarpa","to":"Ircinia strobilina","value":1},
{"from":"Leucothoe spinicarpa","to":"Niphates digitalis","value":1},
{"from":"Leucothoe spinicarpa","to":"Niphates erecta","value":1},
{"from":"Leucothoe spinicarpa","to":"Spheciospongia vesparium","value":1},
{"from":"Leucothoe ubouhu","to":"Spongia (Spongia) obliqua","value":1},
{"from":"Leucothoe wuriti","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Libinia dubia","to":"Amphimedon viridis","value":1},
{"from":"Lysmata pederseni","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Megalobrachium soriatum","to":"Ircinia strobilina","value":1},
{"from":"Melybia thalamita","to":"Aplysina lacunosa","value":1},
{"from":"Mithrax forceps","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Mithrax forceps","to":"Dragmacidon lunaecharta","value":1},
{"from":"Mithrax forceps","to":"Ircinia felix","value":1},
{"from":"Mithrax forceps","to":"Ircinia strobilina","value":1},
{"from":"Munida irrasa","to":"Aplysina lacunosa","value":1},
{"from":"Nebalia villalobosi","to":"Ircinia felix","value":1},
{"from":"Neogonodactylus austrinus","to":"Ircinia strobilina","value":1},
{"from":"Neogonodactylus oerstedii","to":"Ircinia strobilina","value":1},
{"from":"Neopontonides beaufortensis","to":"Haliclona (Haliclona) oculata","value":1},
{"from":"Nikoides schmitti","to":"Ircinia strobilina","value":1},
{"from":"Pachycheles ackleianus","to":"Ircinia felix","value":1},
{"from":"Pachycheles ackleianus","to":"Ircinia strobilina","value":1},
{"from":"Pachycheles ackleianus","to":"Spheciospongia vesparium","value":1},
{"from":"Pachycheles monilifer","to":"Ircinia strobilina","value":1},
{"from":"Pachycheles sp.","to":"Aplysina archeri","value":1},
{"from":"Pachycheles sp.","to":"Aplysina lacunosa","value":1},
{"from":"Paguristes tortugae","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Pagurus brevidactylus","to":"Aplysina archeri","value":1},
{"from":"Pagurus brevidactylus","to":"Aplysina lacunosa","value":1},
{"from":"Pagurus brevidactylus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Pagurus brevidactylus","to":"Dragmacidon lunaecharta","value":1},
{"from":"Pagurus brevidactylus","to":"Ircinia felix","value":1},
{"from":"Pagurus brevidactylus","to":"Ircinia strobilina","value":1},
{"from":"Pagurus provenzanoi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Paracerceis caudata","to":"Amphimedon viridis","value":1},
{"from":"Paracerceis caudata","to":"Aplysina insularis","value":1},
{"from":"Paracerceis caudata","to":"Cliona celata","value":1},
{"from":"Parahaustorius attenuatus","to":"Aiolochroia crassa","value":1},
{"from":"Parahaustorius attenuatus","to":"Aplysina fistularis","value":1},
{"from":"Parahaustorius attenuatus","to":"Dragmacidon lunaecharta","value":1},
{"from":"Parahaustorius attenuatus","to":"Ircinia felix","value":1},
{"from":"Parahaustorius attenuatus","to":"Ircinia strobilina","value":1},
{"from":"Paraliomera longimana","to":"Aplysina lacunosa","value":1},
{"from":"Periclimenaeus bredini","to":"Amphimedon compressa","value":1},
{"from":"Periclimenaeus bredini","to":"Aplysina archeri","value":1},
{"from":"Periclimenaeus bredini","to":"Aplysina fistularis","value":1},
{"from":"Periclimenaeus bredini","to":"Aplysina lacunosa","value":1},
{"from":"Periclimenaeus bredini","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Periclimenaeus bredini","to":"Dragmacidon lunaecharta","value":1},
{"from":"Periclimenaeus bredini","to":"Ircinia felix","value":1},
{"from":"Periclimenaeus bredini","to":"Ircinia strobilina","value":1},
{"from":"Periclimenaeus bredini","to":"Sarcotragus fasciculatus","value":1},
{"from":"Periclimenaeus caraibicus","to":"Aiolochroia crassa","value":1},
{"from":"Periclimenaeus caraibicus","to":"Amphimedon compressa","value":1},
{"from":"Periclimenaeus caraibicus","to":"Aplysina fistularis","value":1},
{"from":"Periclimenaeus caraibicus","to":"Aplysina lacunosa","value":1},
{"from":"Periclimenaeus caraibicus","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Periclimenaeus caraibicus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Periclimenaeus caraibicus","to":"Callyspongia (Cladochalina) plicifera","value":1},
{"from":"Periclimenaeus caraibicus","to":"Dysidea variabilis","value":1},
{"from":"Periclimenaeus caraibicus","to":"Monanchora arbuscula","value":1},
{"from":"Periclimenaeus caraibicus","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Periclimenaeus caraibicus","to":"Neopetrosia rosariensis","value":1},
{"from":"Periclimenaeus caraibicus","to":"Niphates erecta","value":1},
{"from":"Periclimenaeus caraibicus","to":"Tedania (Tedania) ignis","value":1},
{"from":"Periclimenaeus chacei","to":"Ircinia strobilina","value":1},
{"from":"Periclimenaeus pearsei","to":"Ircinia strobilina","value":1},
{"from":"Periclimenaeus pearsei","to":"Spongia (Spongia) officinalis","value":1},
{"from":"Periclimenaeus perlatus","to":"Aiolochroia crassa","value":1},
{"from":"Periclimenaeus perlatus","to":"Aplysina archeri","value":1},
{"from":"Periclimenaeus perlatus","to":"Aplysina fistularis","value":1},
{"from":"Periclimenaeus perlatus","to":"Aplysina insularis","value":1},
{"from":"Periclimenaeus perlatus","to":"Aplysina lacunosa","value":1},
{"from":"Periclimenaeus perlatus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Periclimenaeus perlatus","to":"Callyspongia (Cladochalina) armigera","value":1},
{"from":"Periclimenaeus perlatus","to":"Ircinia felix","value":1},
{"from":"Periclimenaeus schmitti","to":"Aplysina fistularis","value":1},
{"from":"Periclimenaeus schmitti","to":"Ircinia strobilina","value":1},
{"from":"Periclimenaeus schmitti","to":"Monanchora arbuscula","value":1},
{"from":"Periclimenaeus schmitti","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Periclimenaeus wilsoni","to":"Geodia neptuni","value":1},
{"from":"Periclimenaeus wilsoni","to":"Ircinia felix","value":1},
{"from":"Periclimenes iridescens","to":"Agelas dispar","value":1},
{"from":"Periclimenes iridescens","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Periclimenes iridescens","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Periclimenes iridescens","to":"Cliona celata","value":1},
{"from":"Periclimenes iridescens","to":"Dragmacidon lunaecharta","value":1},
{"from":"Periclimenes iridescens","to":"Haliclona (Haliclona) oculata","value":1},
{"from":"Periclimenes iridescens","to":"Ircinia strobilina","value":1},
{"from":"Periclimenes iridescens","to":"Neofibularia nolitangere","value":1},
{"from":"Periclimenes iridescens","to":"Neopetrosia rosariensis","value":1},
{"from":"Periclimenes iridescens","to":"Sarcotragus fasciculatus","value":1},
{"from":"Periclimenes sandyi","to":"Aplysina fistularis","value":1},
{"from":"Periclimenes sandyi","to":"Batzella sp.","value":1},
{"from":"Periclimenes sandyi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Periclimenes sandyi","to":"Clathria (Clathria) foliacea","value":1},
{"from":"Periclimenes sandyi","to":"Igernella notabilis","value":1},
{"from":"Periclimenes sandyi","to":"Ircinia felix","value":1},
{"from":"Periclimenes sandyi","to":"Monanchora arbuscula","value":1},
{"from":"Periclimenes sandyi","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Periclimenes sandyi","to":"Verongula reiswigi","value":1},
{"from":"Periclimenes sp.","to":"Niphates amorpha","value":1},
{"from":"Petrolisthes caribensis","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Petrolisthes politus","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Petrolisthes politus","to":"Ircinia strobilina","value":1},
{"from":"Pilumnus dasypodus","to":"Dragmacidon lunaecharta","value":1},
{"from":"Pilumnus dasypodus","to":"Ircinia strobilina","value":1},
{"from":"Pilumnus sp.","to":"Aplysina archeri","value":1},
{"from":"Pilumnus sp.","to":"Aplysina lacunosa","value":1},
{"from":"Pinnotheres shoemakeri","to":"Ircinia strobilina","value":1},
{"from":"Platypodiella spectabilis","to":"Aplysina archeri","value":1},
{"from":"Podocerus brasiliensis","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Processa fimbriata","to":"Clathria (Thalysias) curacaoensis","value":1},
{"from":"Processa fimbriata","to":"Ircinia strobilina","value":1},
{"from":"Processa fimbriata","to":"Spheciospongia vesparium","value":1},
{"from":"Pseudamphithoides bacescui","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Pycnogonida sp.","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Seba alvarezi","to":"Ircinia felix","value":1},
{"from":"Seba sp.","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Seba sp. A","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Seba sp. B","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Stenetriidae incertae sedis occidentale","to":"Agelas dispar","value":1},
{"from":"Stenetriidae incertae sedis occidentale","to":"Aplysina insularis","value":1},
{"from":"Stenetriidae incertae sedis occidentale","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Stenopus scutellatus","to":"Aplysina archeri","value":1},
{"from":"Stenothoe georgiana","to":"Cliona celata","value":1},
{"from":"Synalpheus agelas","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus agelas","to":"Agelas dispar","value":1},
{"from":"Synalpheus agelas","to":"Monanchora arbuscula","value":1},
{"from":"Synalpheus androsi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus androsi","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus androsi","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus androsi","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus apioceros","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus apioceros","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Synalpheus apioceros","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus belizensis","to":"Hyrtios proteus","value":1},
{"from":"Synalpheus belizensis","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus belizensis","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus bocas","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus bocas","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus bocas","to":"Xestospongia sp.","value":1},
{"from":"Synalpheus bousfieldi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus bousfieldi","to":"Agelas dispar","value":1},
{"from":"Synalpheus bousfieldi","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus bousfieldi","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus bousfieldi","to":"Hyattella sp.","value":1},
{"from":"Synalpheus bousfieldi","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus bousfieldi","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus bousfieldi","to":"Niphates amorpha","value":1},
{"from":"Synalpheus brevicarpus","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus brevicarpus","to":"Amphimedon compressa","value":1},
{"from":"Synalpheus brevicarpus","to":"Aplysina fistularis","value":1},
{"from":"Synalpheus brevicarpus","to":"Batzella sp.","value":1},
{"from":"Synalpheus brevicarpus","to":"Dysidea sp.","value":1},
{"from":"Synalpheus brevicarpus","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus brevicarpus","to":"Ircinia felix","value":1},
{"from":"Synalpheus brevicarpus","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus brevicarpus","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus brevicarpus","to":"Monanchora arbuscula","value":1},
{"from":"Synalpheus brevicarpus","to":"Mycale (Zygomycale) parishii","value":1},
{"from":"Synalpheus brevicarpus","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus brevicarpus","to":"Niphates erecta","value":1},
{"from":"Synalpheus brevicarpus","to":"Spongia (Spongia) officinalis","value":1},
{"from":"Synalpheus brevicarpus","to":"Spongia (Spongia) tubulifera","value":1},
{"from":"Synalpheus brevifrons","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus brevifrons","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus brooksi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus brooksi","to":"Agelas dispar","value":1},
{"from":"Synalpheus brooksi","to":"Ectyoplasia ferox","value":1},
{"from":"Synalpheus brooksi","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus brooksi","to":"Ircinia felix","value":1},
{"from":"Synalpheus brooksi","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus brooksi","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus brooksi","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus carpenteri","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus carpenteri","to":"Agelas dispar","value":1},
{"from":"Synalpheus chacei","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus chacei","to":"Agelas dispar","value":1},
{"from":"Synalpheus chacei","to":"Ectyoplasia ferox","value":1},
{"from":"Synalpheus chacei","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus chacei","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus chacei","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus chacei","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus chacei","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus chacei","to":"Niphates amorpha","value":1},
{"from":"Synalpheus chacei","to":"Oceanapia sp.","value":1},
{"from":"Synalpheus corallinus","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus dardeaui","to":"Spongia sp.","value":1},
{"from":"Synalpheus dominicensis","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus dominicensis","to":"Clathria (Clathria) foliacea","value":1},
{"from":"Synalpheus dominicensis","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus duffyi","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus duffyi","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus elizabethae","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus filidigitus","to":"Calyx podatypa","value":1},
{"from":"Synalpheus filidigitus","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus filidigitus","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus filidigitus","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus filidigitus","to":"Oceanapia sp.","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Amphimedon compressa","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Aplysina fistularis","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Aplysina lacunosa","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Geodia neptuni","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Ircinia campana","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Ircinia felix","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Monanchora arbuscula","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Niphates erecta","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Tedania (Tedania) ignis","value":1},
{"from":"Synalpheus fritzmuelleri","to":"Verongula reiswigi","value":1},
{"from":"Synalpheus goodei","to":"Agelas dispar","value":1},
{"from":"Synalpheus goodei","to":"Calyx podatypa","value":1},
{"from":"Synalpheus goodei","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus goodei","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus goodei","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus heardi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus heardi","to":"Agelas dispar","value":1},
{"from":"Synalpheus heardi","to":"Ircinia sp.","value":1},
{"from":"Synalpheus heardi","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus hemphilli","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Synalpheus hemphilli","to":"Callyspongia (Cladochalina) plicifera","value":1},
{"from":"Synalpheus hemphilli","to":"Chalinula variabilis","value":1},
{"from":"Synalpheus hemphilli","to":"Igernella notabilis","value":1},
{"from":"Synalpheus hemphilli","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus herricki","to":"Agelas dispar","value":1},
{"from":"Synalpheus herricki","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus herricki","to":"Ectyoplasia ferox","value":1},
{"from":"Synalpheus herricki","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus hoetjesi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus hoetjesi","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus idios","to":"Hyrtios proteus","value":1},
{"from":"Synalpheus idios","to":"Spongia sp.","value":1},
{"from":"Synalpheus irie","to":"Auletta sycinularia","value":1},
{"from":"Synalpheus kuadramanus","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus longicarpus","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus longicarpus","to":"Agelas dispar","value":1},
{"from":"Synalpheus longicarpus","to":"Calyx podatypa","value":1},
{"from":"Synalpheus longicarpus","to":"Neopetrosia rosariensis","value":1},
{"from":"Synalpheus longicarpus","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus mcclendoni","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus mcclendoni","to":"Agelas dispar","value":1},
{"from":"Synalpheus mcclendoni","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus mcclendoni","to":"Auletta sycinularia","value":1},
{"from":"Synalpheus mcclendoni","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus mcclendoni","to":"Hyrtios proteus","value":1},
{"from":"Synalpheus mcclendoni","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus microneptunus","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus microneptunus","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus minus","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus minus","to":"Amphimedon compressa","value":1},
{"from":"Synalpheus minus","to":"Aplysina archeri","value":1},
{"from":"Synalpheus minus","to":"Aplysina fistularis","value":1},
{"from":"Synalpheus minus","to":"Aplysina lacunosa","value":1},
{"from":"Synalpheus minus","to":"Dragmacidon lunaecharta","value":1},
{"from":"Synalpheus minus","to":"Geodia neptuni","value":1},
{"from":"Synalpheus minus","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus minus","to":"Ircinia campana","value":1},
{"from":"Synalpheus minus","to":"Ircinia felix","value":1},
{"from":"Synalpheus minus","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus pandionis","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus pandionis","to":"Agelas dispar","value":1},
{"from":"Synalpheus pandionis","to":"Calyx podatypa","value":1},
{"from":"Synalpheus pandionis","to":"Ectyoplasia ferox","value":1},
{"from":"Synalpheus pandionis","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus pandionis","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus pandionis","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus pandionis","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus pandionis","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus pandionis","to":"Lissodendoryx sp.","value":1},
{"from":"Synalpheus pandionis","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus pandionis","to":"Spirastrella sp.","value":1},
{"from":"Synalpheus paraneptunus","to":"Agelas dispar","value":1},
{"from":"Synalpheus paraneptunus","to":"Calyx podatypa","value":1},
{"from":"Synalpheus paraneptunus","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus paraneptunus","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus paraneptunus","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus paraneptunus","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus paraneptunus","to":"Neopetrosia rosariensis","value":1},
{"from":"Synalpheus paraneptunus","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus paraneptunus","to":"Oceanapia sp.","value":1},
{"from":"Synalpheus pectiniger","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus plumosetosus","to":"Auletta sycinularia","value":1},
{"from":"Synalpheus rathbunae","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus rathbunae","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus rathbunae","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus rathbunae","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus rathbunae","to":"Neopetrosia rosariensis","value":1},
{"from":"Synalpheus regalis","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus regalis","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus regalis","to":"Lissodendoryx (Lissodendoryx) colombiensis","value":1},
{"from":"Synalpheus regalis","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus regalis","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus regalis","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus ruetzleri","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus sanctithomae","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus sanctithomae","to":"Auletta sycinularia","value":1},
{"from":"Synalpheus sanctithomae","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus sanctithomae","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus sanctithomae","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus sanctithomae","to":"Lissodendoryx (Lissodendoryx) strongylata","value":1},
{"from":"Synalpheus sanctithomae","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus sanctithomae","to":"Spheciospongia vesparium","value":1},
{"from":"Synalpheus sanctithomae","to":"Xestospongia sp.","value":1},
{"from":"Synalpheus scaphoceris","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus scaphoceris","to":"Ircinia felix","value":1},
{"from":"Synalpheus scaphoceris","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Synalpheus tenuispina","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Synalpheus thele","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus thele","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus thele","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus thele","to":"Spirastrella sp.","value":1},
{"from":"Synalpheus townsendi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus townsendi","to":"Agelas dispar","value":1},
{"from":"Synalpheus townsendi","to":"Aiolochroia crassa","value":1},
{"from":"Synalpheus townsendi","to":"Amphimedon compressa","value":1},
{"from":"Synalpheus townsendi","to":"Aplysina archeri","value":1},
{"from":"Synalpheus townsendi","to":"Aplysina fulva","value":1},
{"from":"Synalpheus townsendi","to":"Aplysina insularis","value":1},
{"from":"Synalpheus townsendi","to":"Aplysina lacunosa","value":1},
{"from":"Synalpheus townsendi","to":"Batzella sp.","value":1},
{"from":"Synalpheus townsendi","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Synalpheus townsendi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Synalpheus townsendi","to":"Clathria (Clathria) foliacea","value":1},
{"from":"Synalpheus townsendi","to":"Dysidea sp.","value":1},
{"from":"Synalpheus townsendi","to":"Dysidea variabilis","value":1},
{"from":"Synalpheus townsendi","to":"Geodia gibberosa","value":1},
{"from":"Synalpheus townsendi","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus townsendi","to":"Ircinia campana","value":1},
{"from":"Synalpheus townsendi","to":"Ircinia strobilina","value":1},
{"from":"Synalpheus townsendi","to":"Monanchora arbuscula","value":1},
{"from":"Synalpheus townsendi","to":"Mycale (Arenochalina) laxissima","value":1},
{"from":"Synalpheus townsendi","to":"Neofibularia nolitangere","value":1},
{"from":"Synalpheus townsendi","to":"Pandaros acanthifolium","value":1},
{"from":"Synalpheus townsendi","to":"Phorbas amaranthus","value":1},
{"from":"Synalpheus townsendi","to":"Sarcotragus fasciculatus","value":1},
{"from":"Synalpheus ul","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus ul","to":"Hyattella intestinalis","value":1},
{"from":"Synalpheus ul","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus ul","to":"Lissodendoryx sp.","value":1},
{"from":"Synalpheus ul","to":"Neopetrosia proxima","value":1},
{"from":"Synalpheus ul","to":"Neopetrosia subtriangularis","value":1},
{"from":"Synalpheus ul","to":"Spirastrella sp.","value":1},
{"from":"Synalpheus ul","to":"Xestospongia sp.","value":1},
{"from":"Synalpheus williamsi","to":"Agelas clathrodes","value":1},
{"from":"Synalpheus williamsi","to":"Hymeniacidon caerulea","value":1},
{"from":"Synalpheus yano","to":"Hymeniacidon caerulea","value":1},
{"from":"Thor manningi","to":"Agelas dispar","value":1},
{"from":"Thor manningi","to":"Aiolochroia crassa","value":1},
{"from":"Thor manningi","to":"Aplysina archeri","value":1},
{"from":"Thor manningi","to":"Aplysina lacunosa","value":1},
{"from":"Thor manningi","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Thor manningi","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Thor manningi","to":"Dragmacidon lunaecharta","value":1},
{"from":"Thor manningi","to":"Ircinia strobilina","value":1},
{"from":"Thor manningi","to":"Sarcotragus fasciculatus","value":1},
{"from":"Typton distinctus","to":"Aplysina lacunosa","value":1},
{"from":"Typton prionurus","to":"Callyspongia (Callyspongia) fallax","value":1},
{"from":"Typton prionurus","to":"Callyspongia (Cladochalina) aculeata","value":1},
{"from":"Typton prionurus","to":"Tedania (Tedania) ignis","value":1},
{"from":"Typton tortugae","to":"Ircinia strobilina","value":1},
{"from":"Typton tortugae","to":"Spheciospongia vesparium","value":1},
{"from":"Upogebia acanthura","to":"Agelas clathrodes","value":1},
{"from":"Upogebia acanthura","to":"Agelas sceptrum","value":1},
{"from":"Upogebia annae","to":"Xestospongia sp.","value":1},
{"from":"Upogebia casis","to":"Xestospongia sp.","value":1}







]



chart.dataFields.fromName = "from";
chart.dataFields.toName = "to";
chart.dataFields.value = "value";


chart.nodePadding = .9;
chart.minNodeSize = 0.005;
chart.startAngle = 45;
chart.endAngle = chart.startAngle + 360;
chart.fontSize = 9;



var nodeTemplate = chart.nodes.template;
// nodeTemplate.readerTitle = "Click to show/hide nodes";
nodeTemplate.showTooltip = true;
nodeTemplate.propertyFields.fill = "color";
nodeTemplate.tooltipText = "{from}->{total}";
nodeTemplate.draggable= false;
nodeTemplate.clickable=false;


// when rolled over the node, make all the links rolled-over
nodeTemplate.events.on("over", function(event) {    
    var node = event.target;
    node.outgoingDataItems.each(function(dataItem) {
        if(dataItem.toNode){
            dataItem.link.isHover = true;
            dataItem.toNode.label.isHover = true;
        }
    })

    node.incomingDataItems.each(function(dataItem) {
        if(dataItem.fromNode){
            dataItem.link.isHover = true;
            dataItem.fromNode.label.isHover = true;
        }
    }) 

    node.label.isHover = true;   
})


// when rolled out from the node, make all the links rolled-out
nodeTemplate.events.on("out", function(event) {
    var node = event.target;
    node.outgoingDataItems.each(function(dataItem) {        
        if(dataItem.toNode){
            dataItem.link.isHover = false;                
            dataItem.toNode.label.isHover = false;
        }
    })
    node.incomingDataItems.each(function(dataItem) {
        if(dataItem.fromNode){
            dataItem.link.isHover = true;
           dataItem.fromNode.label.isHover = false;
        }
    })

    node.label.isHover = false;
})

var label = nodeTemplate.label;
label.relativeRotation = 90;
label.fillOpacity = 0.5;
let labelHS = label.states.create("hover");
labelHS.properties.fillOpacity = 1;
nodeTemplate.cursorOverStyle = am4core.MouseCursorStyle.pointer;
// this adapter makes non-main character nodes to be filled with color of the main character which he/she kissed most

  

// link template 
var linkTemplate = chart.links.template;
linkTemplate.strokeOpacity = 0;
linkTemplate.fillOpacity = 0.75;
//linkTemplate.tooltipText = "{fromTotal} guest of {value}";

var hoverState = linkTemplate.states.create("hover");
hoverState.properties.fillOpacity = .9;
hoverState.properties.strokeOpacity = 1;






// data credit label
var creditLabel = chart.chartContainer.createChild(am4core.TextLink);
creditLabel.text = "Data source Pérez-Botello & Simões, 2019";
creditLabel.url = "https://zenodo.org/record/3333023";
creditLabel.y = am4core.percent(99);
creditLabel.x = am4core.percent(99);
creditLabel.horizontalCenter = "right";
creditLabel.verticalCenter = "bottom";
creditLabel.fontSize= "12px"; 


            chart.exporting.menu = new am4core.ExportMenu();
            chart.exporting.menu.items = [{
                "label": "...",
                "menu": [
                    {
                        "label": "Imagen",
                        "menu": [
                            { "type": "svg", "label": "SVG" },
                            { "type": "png", "label": "PNG" },
                            { "type": "jpg", "label": "JPG" },
                            { "type": "gif", "label": "GIF" },
                            { "type": "pdf", "label": "PDF" }
                        ]
                    }, 
                    {
                        "label": "Imprimir", "type": "print"
                    }
                ]
            }];
